name: Python Continuos Integration

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Export GitHub secrets to .env file
        run: |
          echo PRIVATE_KEY=${{ secrets.MY_PRIVATE_KEY }} >> .env
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install eth-brownie

      - name: Run tests
        run: brownie test
